server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    use-legacy-processing: true
  profiles:
    include: common
  datasource:
    username: root
    password: Nguyenhuylong@
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/graduation_project?useUnicode=yes&characterEncoding=UTF-8
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ketmax121@gmail.com
    password: bpwgcdgsvhwqeikj
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

inventory:
  logs:
    path: ./logs/development
